on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format16
        run: |
            sudo apt-get update
            apt-get search clang-format
            sudo apt-get install clang-format-16
      - name: Run tests
        run: ./ci.sh
        shell: bash
