on:
    push:
        tags:
            - '*'

permissions:
  contents: write

jobs:
  build:
    name: Publish package
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Prepare deps
      run: ./get-deps.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mellow-with-deps.tar.gz
        asset_name: mellow-with-deps-$tag.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
